import type { BilingualField } from './paper';

/**
 * Research Domain — hierarchical classification system.
 *
 * Designed for LLM auto-maintenance:
 * - When a new domain is discovered, create a ResearchDomain with keywords
 * - LLM re-scans all existing papers' title/summary against keywords
 * - Matched papers get linked via paperIds / paper.domains
 */
export interface ResearchDomain {
  /** Unique identifier, hierarchical: "nlp.llm.reasoning" */
  id: string;
  name: BilingualField;
  description: BilingualField;

  /** Hierarchy */
  parentId: string | null;
  children: string[];

  /** Cross-links to related domains */
  relatedDomainIds: string[];

  /** Keywords for auto-classification (LLM uses these as seed terms) */
  keywords: string[];
  /** Negative keywords — papers containing these are excluded */
  excludeKeywords?: string[];

  /** Linked papers */
  paperIds: string[];

  /** Metadata */
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}
